### ISSUE TITLE
Clock and Date option - Wrong Date

### ISSUE THREAD

**Issue by ItsProbablyAndy** [framedsc/HOFWallpaper#1]
Date shows 1-7-2023
Current date is August 1st 2023 so assuming the everywhere but America date format, it's out by a month.

![image](https://github.com/framedsc/HOFWallpaper/assets/116114419/6096d3fa-4804-4063-8e72-22a9db67b847)

**Comment by originalnicodr** [comment]
> An integer, between 0 and 11, representing the month for the given date according to local time: 0 for January, 1 for February, and so on

Fucking javascript man I swear.

Fixed in f0a34caddf972b12b0e67c204e18aa3e49815014
