### ISSUE TITLE
Clock and Date option - Time Format

### ISSUE THREAD

**Issue by ItsProbablyAndy** [framedsc/HOFWallpaper#2]
Couldn't get a screenshot but the formatting of the time displays as HH:MM but when the M value is less than two characters, it diplays as HH:M which is visually inconsistent. 

For example at 22:05, the clock is displayed as 22:5.

**Comment by ItsProbablyAndy** [comment]
Same issue for the HH side of the format.

![image](https://github.com/framedsc/HOFWallpaper/assets/116114419/cdebc84b-d872-408b-98b3-c4cd0dc205f6)

**Comment by originalnicodr** [comment]
Fixed in f0a34caddf972b12b0e67c204e18aa3e49815014
